package testingproject;

public class CalculatorFrame extends javax.swing.JFrame
{
    Calculator calc = new Calculator() ;
    double firstNum = 0; 
    double secNum = 0; 
    double result = 0; 
    String operation = "";
    boolean Flag = false; 
    boolean decFlag = false;
    boolean oprFlag = false;
    boolean Flag_Area = false;
    boolean Flag_Speed = false;
    boolean Flag_Time = false;
    boolean Flag_Length = false;
    boolean Flag_Mass = false;
    boolean Flag_Temp = false;
    
    public CalculatorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConversionPnl = new javax.swing.JPanel();
        LengthCombo2 = new javax.swing.JComboBox<>();
        AreaText2 = new javax.swing.JTextField();
        AreaText1 = new javax.swing.JTextField();
        LengthCombo1 = new javax.swing.JComboBox<>();
        LengthText1 = new javax.swing.JTextField();
        AreaCombo2 = new javax.swing.JComboBox<>();
        TimeText2 = new javax.swing.JTextField();
        TimeText1 = new javax.swing.JTextField();
        AreaCombo1 = new javax.swing.JComboBox<>();
        MassText1 = new javax.swing.JTextField();
        LengthLbl = new javax.swing.JLabel();
        TimeCombo1 = new javax.swing.JComboBox<>();
        MassText2 = new javax.swing.JTextField();
        AreaLbl = new javax.swing.JLabel();
        TimeCombo2 = new javax.swing.JComboBox<>();
        TempText1 = new javax.swing.JTextField();
        TempCombo1 = new javax.swing.JComboBox<>();
        TempText2 = new javax.swing.JTextField();
        TempCombo2 = new javax.swing.JComboBox<>();
        SpeedText1 = new javax.swing.JTextField();
        SpeedCombo1 = new javax.swing.JComboBox<>();
        SpeedCombo2 = new javax.swing.JComboBox<>();
        TempLbl = new javax.swing.JLabel();
        SpeedText2 = new javax.swing.JTextField();
        MassLbl = new javax.swing.JLabel();
        MassCombo2 = new javax.swing.JComboBox<>();
        MassCombo1 = new javax.swing.JComboBox<>();
        TimeLbl = new javax.swing.JLabel();
        SpeedLbl = new javax.swing.JLabel();
        ButtonConvert = new javax.swing.JButton();
        LengthText2 = new javax.swing.JTextField();
        FromLbl = new javax.swing.JLabel();
        ToLbl = new javax.swing.JLabel();
        CalculatorPnl = new javax.swing.JPanel();
        Button7 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        ButtonDecimal = new javax.swing.JButton();
        ButtonDivide = new javax.swing.JButton();
        ButtonAdd = new javax.swing.JButton();
        ButtonMultiply = new javax.swing.JButton();
        ButtonMinus = new javax.swing.JButton();
        ButtonClear = new javax.swing.JButton();
        ButtonModulus = new javax.swing.JButton();
        ButtonEquals = new javax.swing.JButton();
        ButtonRoot = new javax.swing.JButton();
        ButtonPower = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Screen = new javax.swing.JTextField();
        ButtonFact = new javax.swing.JButton();
        ButtonSign = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator & Units Converter");
        setResizable(false);

        LengthCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centimeters", "Meters", "Kilometers", "Inches", "Miles", " " }));
        LengthCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LengthCombo2ActionPerformed(evt);
            }
        });

        AreaText2.setEditable(false);
        AreaText2.setBackground(new java.awt.Color(255, 255, 255));
        AreaText2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AreaText2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AreaText1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AreaText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AreaText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AreaText1KeyTyped(evt);
            }
        });

        LengthCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centimeters", "Meters", "Kilometers", "Inches", "Miles", " " }));
        LengthCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LengthCombo1ActionPerformed(evt);
            }
        });

        LengthText1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LengthText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LengthText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LengthText1ActionPerformed(evt);
            }
        });
        LengthText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LengthText1KeyTyped(evt);
            }
        });

        AreaCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Square centimeters", "Square meters", "Square kilometers", "Square miles" }));
        AreaCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaCombo2ActionPerformed(evt);
            }
        });

        TimeText2.setEditable(false);
        TimeText2.setBackground(new java.awt.Color(255, 255, 255));
        TimeText2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TimeText2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TimeText1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TimeText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TimeText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TimeText1KeyTyped(evt);
            }
        });

        AreaCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Square centimeters", "Square meters", "Square kilometers", "Square miles" }));

        MassText1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        MassText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MassText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MassText1KeyTyped(evt);
            }
        });

        LengthLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LengthLbl.setText("Length");

        TimeCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seconds", "Minutes", "Hours", "Days", "Weeks", "Years", " " }));

        MassText2.setEditable(false);
        MassText2.setBackground(new java.awt.Color(255, 255, 255));
        MassText2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        MassText2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AreaLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AreaLbl.setText("Area");

        TimeCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seconds", "Minutes", "Hours", "Days", "Weeks", "Years", " " }));

        TempText1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TempText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TempText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TempText1KeyTyped(evt);
            }
        });

        TempCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Kelvin" }));

        TempText2.setEditable(false);
        TempText2.setBackground(new java.awt.Color(255, 255, 255));
        TempText2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TempText2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TempCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Kelvin" }));
        TempCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempCombo2ActionPerformed(evt);
            }
        });

        SpeedText1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SpeedText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SpeedText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpeedText1ActionPerformed(evt);
            }
        });
        SpeedText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SpeedText1KeyTyped(evt);
            }
        });

        SpeedCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cm/s", "m/s", "km/h", "miles/h", " " }));

        SpeedCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cm/s", "m/s", "km/h", "miles/h", " " }));

        TempLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TempLbl.setText("Temperature");

        SpeedText2.setEditable(false);
        SpeedText2.setBackground(new java.awt.Color(255, 255, 255));
        SpeedText2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SpeedText2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        MassLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MassLbl.setText("Mass");

        MassCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Milligrams", "Grams", "Kilograms", "Pounds", " " }));

        MassCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Milligrams", "Grams", "Kilograms", "Pounds", " " }));

        TimeLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TimeLbl.setText("Time");

        SpeedLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SpeedLbl.setText("Speed");

        ButtonConvert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonConvert.setText("Convert");
        ButtonConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConvertActionPerformed(evt);
            }
        });

        LengthText2.setEditable(false);
        LengthText2.setBackground(new java.awt.Color(255, 255, 255));
        LengthText2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LengthText2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        FromLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FromLbl.setText("From");

        ToLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ToLbl.setText("To");

        javax.swing.GroupLayout ConversionPnlLayout = new javax.swing.GroupLayout(ConversionPnl);
        ConversionPnl.setLayout(ConversionPnlLayout);
        ConversionPnlLayout.setHorizontalGroup(
            ConversionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConversionPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ConversionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TempLbl)
                    .addComponent(SpeedLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MassLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AreaLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LengthLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TimeLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConversionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonConvert, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ConversionPnlLayout.createSequentialGroup()
                        .addGroup(ConversionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TempText1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LengthText1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AreaText1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TimeText1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MassText1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpeedText1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ConversionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MassCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TempCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TimeCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AreaCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LengthCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpeedCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConversionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConversionPnlLayout.createSequentialGroup()
                        .addComponent(LengthText2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LengthCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ConversionPnlLayout.createSequentialGroup()
                        .addGroup(ConversionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ConversionPnlLayout.createSequentialGroup()
                                .addComponent(AreaText2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AreaCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ConversionPnlLayout.createSequentialGroup()
                                .addComponent(SpeedText2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SpeedCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ConversionPnlLayout.createSequentialGroup()
                                .addComponent(TempText2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TempCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ConversionPnlLayout.createSequentialGroup()
                                .addComponent(MassText2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MassCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ConversionPnlLayout.createSequentialGroup()
                                .addComponent(TimeText2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TimeCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(ConversionPnlLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(FromLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ToLbl)
                .addGap(168, 168, 168))
        );
        ConversionPnlLayout.setVerticalGroup(
            ConversionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConversionPnlLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(ConversionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FromLbl)
                    .addComponent(ToLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ConversionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConversionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LengthCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LengthCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LengthText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LengthText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LengthLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConversionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AreaCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AreaCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AreaText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AreaText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AreaLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConversionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeLbl)
                    .addComponent(TimeText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConversionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MassCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MassCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MassText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MassLbl)
                    .addComponent(MassText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConversionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TempCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TempCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TempText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TempLbl)
                    .addComponent(TempText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(ConversionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpeedCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpeedText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpeedCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpeedText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpeedLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Button7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button7.setText("7");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        Button9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button9.setText("9");
        Button9.setToolTipText("");
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });

        Button8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button8.setText("8");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });

        Button6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button6.setText("6");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });

        Button5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button5.setText("5");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });

        Button4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button4.setText("4");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });

        Button3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button3.setText("3");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        Button2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button2.setText("2");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        Button0.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button0.setText("0");
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });

        ButtonDecimal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonDecimal.setText(".");
        ButtonDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDecimalActionPerformed(evt);
            }
        });

        ButtonDivide.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonDivide.setText("÷");
        ButtonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDivideActionPerformed(evt);
            }
        });

        ButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonAdd.setText("+");
        ButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddActionPerformed(evt);
            }
        });

        ButtonMultiply.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonMultiply.setText("X");
        ButtonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMultiplyActionPerformed(evt);
            }
        });

        ButtonMinus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonMinus.setText("-");
        ButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMinusActionPerformed(evt);
            }
        });

        ButtonClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonClear.setText("C");
        ButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClearActionPerformed(evt);
            }
        });

        ButtonModulus.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        ButtonModulus.setText("%");
        ButtonModulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModulusActionPerformed(evt);
            }
        });

        ButtonEquals.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonEquals.setText("=");
        ButtonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEqualsActionPerformed(evt);
            }
        });

        ButtonRoot.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        ButtonRoot.setText("√");
        ButtonRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRootActionPerformed(evt);
            }
        });

        ButtonPower.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        ButtonPower.setText("xⁿ");
        ButtonPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPowerActionPerformed(evt);
            }
        });

        Button1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button1.setText("1");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        Screen.setEditable(false);
        Screen.setBackground(new java.awt.Color(255, 255, 255));
        Screen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Screen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ButtonFact.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonFact.setText("x!");
        ButtonFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFactActionPerformed(evt);
            }
        });

        ButtonSign.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonSign.setText("±");
        ButtonSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CalculatorPnlLayout = new javax.swing.GroupLayout(CalculatorPnl);
        CalculatorPnl.setLayout(CalculatorPnlLayout);
        CalculatorPnlLayout.setHorizontalGroup(
            CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculatorPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalculatorPnlLayout.createSequentialGroup()
                        .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CalculatorPnlLayout.createSequentialGroup()
                                .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CalculatorPnlLayout.createSequentialGroup()
                                        .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CalculatorPnlLayout.createSequentialGroup()
                                        .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CalculatorPnlLayout.createSequentialGroup()
                                        .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CalculatorPnlLayout.createSequentialGroup()
                                        .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(CalculatorPnlLayout.createSequentialGroup()
                                        .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ButtonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(CalculatorPnlLayout.createSequentialGroup()
                                        .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ButtonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(CalculatorPnlLayout.createSequentialGroup()
                                .addComponent(ButtonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CalculatorPnlLayout.createSequentialGroup()
                        .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Screen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CalculatorPnlLayout.createSequentialGroup()
                                .addComponent(ButtonFact, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonSign, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CalculatorPnlLayout.createSequentialGroup()
                                .addComponent(ButtonModulus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonPower, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        CalculatorPnlLayout.setVerticalGroup(
            CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculatorPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Screen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonFact, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSign, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonModulus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPower, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CalculatorPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConversionPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ConversionPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(CalculatorPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        if(!Flag)
        {
            String num = Screen.getText()+"7";  
            Screen.setText(num);
        }
        
        else 
        {
            Flag = false; 
            Screen.setText("");
            String num = Screen.getText()+"7";  
            Screen.setText(num);    
        }
        oprFlag = true;
        if(!Screen.getText().contains("."))
            decFlag = false;
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        if(!Flag)
        {
            String num = Screen.getText()+"9";  
            Screen.setText(num);
        }
        
        else 
        {
            Flag = false; 
            Screen.setText("");
            String num = Screen.getText()+"9";  
            Screen.setText(num);    
        }
        oprFlag = true;
        if(!Screen.getText().contains("."))
            decFlag = false;
    }//GEN-LAST:event_Button9ActionPerformed

    private void AreaCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaCombo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaCombo2ActionPerformed

    private void LengthCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LengthCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LengthCombo1ActionPerformed

    private void LengthCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LengthCombo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LengthCombo2ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        if(!Flag)
        {
            String num = Screen.getText()+"8";  
            Screen.setText(num);
        }
        
        else 
        {
            Flag = false; 
            Screen.setText("");
            String num = Screen.getText()+"8";  
            Screen.setText(num);    
        }
        oprFlag = true;
        if(!Screen.getText().contains("."))
            decFlag = false;
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        if(!Flag)
        {
            String num = Screen.getText()+"6";  
            Screen.setText(num);
        }
        
        else 
        {
            Flag = false; 
            Screen.setText("");
            String num = Screen.getText()+"6";  
            Screen.setText(num);    
        }
        oprFlag = true;
        if(!Screen.getText().contains("."))
            decFlag = false;
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        if(!Flag)
        {
            String num = Screen.getText()+"5";  
            Screen.setText(num);
        }
        
        else 
        {
            Flag = false; 
            Screen.setText("");
            String num = Screen.getText()+"5";  
            Screen.setText(num);    
        }
        oprFlag = true;
        if(!Screen.getText().contains("."))
            decFlag = false;
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        if(!Flag)
        {
            String num = Screen.getText()+"4";  
            Screen.setText(num);
        }
        
        else 
        {
            Flag = false; 
            Screen.setText("");
            String num = Screen.getText()+"4";  
            Screen.setText(num);    
        }
        oprFlag = true; 
        if(!Screen.getText().contains("."))
            decFlag = false;
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        if(!Flag)
        {
            String num = Screen.getText()+"3";  
            Screen.setText(num);
        }
        
        else 
        {
            Flag = false; 
            Screen.setText("");
            String num = Screen.getText()+"3";  
            Screen.setText(num);    
        }
        oprFlag = true;
        if(!Screen.getText().contains("."))
            decFlag = false;
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        if(!Flag)
        {
            String num = Screen.getText()+"1";  
            Screen.setText(num);
        }
        
        else 
        {
            Flag = false; 
            Screen.setText("");
            String num = Screen.getText()+"1";  
            Screen.setText(num);    
        }
        oprFlag = true;
        if(!Screen.getText().contains("."))
            decFlag = false;
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        if(!Flag)
        {
            String num = Screen.getText()+"2";  
            Screen.setText(num);
        }
        
        else 
        {
            Flag = false; 
            Screen.setText("");
            String num = Screen.getText()+"2";  
            Screen.setText(num);    
        }

        oprFlag = true;    
        if(!Screen.getText().contains("."))
            decFlag = false;
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        if(!Flag)
        {
            String num = Screen.getText()+"0";  
            Screen.setText(num);
        }
        
        else 
        {
            Flag = false; 
            Screen.setText("");
            String num = Screen.getText()+"0";  
            Screen.setText(num);    
        }
        
        oprFlag = true;     
        if(!Screen.getText().contains("."))
            decFlag = false;
    }//GEN-LAST:event_Button0ActionPerformed

    private void ButtonDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDecimalActionPerformed
        if(!decFlag)
        {
            Screen.setText(Screen.getText()+".");
            decFlag = true; 
        }
    }//GEN-LAST:event_ButtonDecimalActionPerformed

    private void ButtonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDivideActionPerformed
        if(oprFlag)
        {
            firstNum = Double.parseDouble(Screen.getText()); 
            operation = "/";
            Flag = true; 
            decFlag = false;
        }
    }//GEN-LAST:event_ButtonDivideActionPerformed

    private void ButtonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEqualsActionPerformed

        if(oprFlag)
        {
            String answer; 
            secNum = Double.parseDouble(Screen.getText());
            if ("+".equals(operation))
            {
                result = calc.add(firstNum, secNum); 
                answer = String.valueOf(result); 
                Screen.setText(answer);
                firstNum = 0; 
                secNum = 0; 
                result = 0; 
                operation = ""; 
                Flag = true;
            }

            else if ("-".equals(operation))
            {
                result =  calc.subtract(firstNum, secNum); 
                answer = String.valueOf(result); 
                Screen.setText(answer);
                firstNum = 0; 
                secNum = 0; 
                result = 0; 
                operation = ""; 
                Flag = true;
            }

            else if ("*".equals(operation))
            {
                result =  calc.multiply(firstNum, secNum); 
                answer = String.valueOf(result); 
                Screen.setText(answer);
                firstNum = 0; 
                secNum = 0; 
                result = 0; 
                operation = ""; 
                Flag = true;
            }

            else if ("/".equals(operation))
            {
                result =  calc.divide(firstNum, secNum); 
                answer = String.valueOf(result); 
                Screen.setText(answer);
                firstNum = 0; 
                secNum = 0; 
                result = 0; 
                operation = ""; 
                Flag = true;
            }

            else if ("^".equals(operation))
            {
                result = calc.power(firstNum, secNum); 
                answer = String.valueOf(result); 
                Screen.setText(answer);
                firstNum = 0; 
                secNum = 0; 
                result = 0; 
                operation = ""; 
                Flag = true;         
            }

            else if ("%".equals(operation))
            {
                result = calc.modulus(firstNum,secNum); 
                answer = String.valueOf(result); 
                Screen.setText(answer);
                firstNum = 0; 
                secNum = 0; 
                result = 0; 
                operation = ""; 
                Flag = true; 
            }
        }
        
        if(Screen.getText().contains("."))
            decFlag = true;
        
        else
            decFlag = false;
    }//GEN-LAST:event_ButtonEqualsActionPerformed

    private void ButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddActionPerformed
        if(oprFlag)
        {
            firstNum = Double.parseDouble(Screen.getText()); 
            operation = "+";
            Flag = true; 
            decFlag = false; 
        }
    }//GEN-LAST:event_ButtonAddActionPerformed

    private void ButtonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMultiplyActionPerformed
        if(oprFlag)
        {
            firstNum = Double.parseDouble(Screen.getText()); 
            operation = "*";
            Flag = true; 
            decFlag = false;
        }
    }//GEN-LAST:event_ButtonMultiplyActionPerformed

    private void ButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMinusActionPerformed
        if(oprFlag)
        {
            firstNum = Double.parseDouble(Screen.getText()); 
            operation = "-";
            Flag = true;
            decFlag = false;
        }
    }//GEN-LAST:event_ButtonMinusActionPerformed

    private void ButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearActionPerformed
        Screen.setText("");
        oprFlag = false;
    }//GEN-LAST:event_ButtonClearActionPerformed

    private void ButtonModulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModulusActionPerformed
        if(oprFlag)
        {
            firstNum = Double.parseDouble(Screen.getText()); 
            operation = "%";
            Flag = true;
            decFlag = false;
        }
    }//GEN-LAST:event_ButtonModulusActionPerformed

    private void ButtonRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRootActionPerformed
        if(oprFlag)
        {
            firstNum = Double.parseDouble(Screen.getText()); 
            operation = "root";
            result = calc.root(firstNum); 
            String answer = String.valueOf(result); 
            Screen.setText(answer);
            Flag = true;
            
            if(Screen.getText().contains("."))
                decFlag = true;
        
            else
                decFlag = false;   
        }
    }//GEN-LAST:event_ButtonRootActionPerformed

    private void ButtonFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFactActionPerformed
        if(oprFlag)
        {
            firstNum = Double.parseDouble(Screen.getText()); 
            operation = "!";
            result = calc.fact(firstNum); 
            String answer = String.valueOf(result); 
            Screen.setText(answer); 
            Flag = true; 
            
            if(Screen.getText().contains("."))
                decFlag = true;
        
            else
                decFlag = false;
        }
    }//GEN-LAST:event_ButtonFactActionPerformed

    private void ButtonPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPowerActionPerformed
        if(oprFlag)
        {
            firstNum = Double.parseDouble(Screen.getText()); 
            operation = "^";
            Flag = true;
        }
    }//GEN-LAST:event_ButtonPowerActionPerformed

    private void SpeedText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpeedText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpeedText1ActionPerformed

    private void ButtonConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConvertActionPerformed
        double Value = 0;
        String From = "";
        String To = "";
        
        if(!MassText1.getText().equals(""))
        {
            Value = Double.parseDouble(MassText1.getText());
            From = MassCombo1.getItemAt(MassCombo1.getSelectedIndex());
            To = MassCombo2.getItemAt(MassCombo2.getSelectedIndex());
            MassText2.setText(""+calc.Mass.Convert(Value, From, To));
            MassText1.setText("");
            Flag_Mass = false;
        }
        
        if(!AreaText1.getText().equals(""))
        {
            Value = Double.parseDouble(AreaText1.getText());
            From = AreaCombo1.getItemAt(AreaCombo1.getSelectedIndex());
            To = AreaCombo2.getItemAt(AreaCombo2.getSelectedIndex());
            AreaText2.setText(""+calc.Area.Convert(Value, From, To));
            AreaText1.setText("");
            Flag_Area = false;
        }
        
        if(!TimeText1.getText().equals(""))
        {
            Value = Double.parseDouble(TimeText1.getText());
            From = TimeCombo1.getItemAt(TimeCombo1.getSelectedIndex());
            To = TimeCombo2.getItemAt(TimeCombo2.getSelectedIndex());
            TimeText2.setText(""+calc.Time.Convert(Value, From, To));
            TimeText1.setText("");
            Flag_Time = false;
        }
        
        if(!LengthText1.getText().equals(""))
        {
            Value = Double.parseDouble(LengthText1.getText());
            From = LengthCombo1.getItemAt(LengthCombo1.getSelectedIndex());
            To = LengthCombo2.getItemAt(LengthCombo2.getSelectedIndex());
            LengthText2.setText(""+calc.Length.Convert(Value, From, To));
            LengthText1.setText("");
            Flag_Length = false;
        }
        
        if(!TempText1.getText().equals(""))
        {
            Value = Double.parseDouble(TempText1.getText());
            From = TempCombo1.getItemAt(TempCombo1.getSelectedIndex());
            To = TempCombo2.getItemAt(TempCombo2.getSelectedIndex());
            TempText2.setText(""+calc.Temperature.Convert(Value, From, To));
            TempText1.setText("");
            Flag_Temp = false;
        }
        
        if(!SpeedText1.getText().equals(""))
        {
            Value = Double.parseDouble(SpeedText1.getText());
            From = SpeedCombo1.getItemAt(SpeedCombo1.getSelectedIndex());
            To = SpeedCombo2.getItemAt(SpeedCombo2.getSelectedIndex());
            SpeedText2.setText(""+calc.Speed.Convert(Value, From, To));
            SpeedText1.setText("");
            Flag_Speed = false;
        }
    }//GEN-LAST:event_ButtonConvertActionPerformed

    private void LengthText1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LengthText1KeyTyped
        char c = evt.getKeyChar();
        if(!Flag_Length)
        {
            if(c == '.')
                Flag_Length = true;
            
            if(!Character.isDigit(c) && c != '.')
                evt.consume();
        }
        
        else
        {
            if(!Character.isDigit(c))
                evt.consume();
        }
    }//GEN-LAST:event_LengthText1KeyTyped

    private void TempCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempCombo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TempCombo2ActionPerformed

    private void LengthText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LengthText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LengthText1ActionPerformed

    private void AreaText1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AreaText1KeyTyped
        char c = evt.getKeyChar();
        if(!Flag_Area)
        {
            if(c == '.')
                Flag_Area = true;
            
            if(!Character.isDigit(c) && c != '.')
                evt.consume();
        }
        
        else
        {
            if(!Character.isDigit(c))
                evt.consume();
        }
    }//GEN-LAST:event_AreaText1KeyTyped

    private void TimeText1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TimeText1KeyTyped
        char c = evt.getKeyChar();
        if(!Flag_Time)
        {
            if(c == '.')
                Flag_Time = true;
            
            if(!Character.isDigit(c) && c != '.')
                evt.consume();
        }
        
        else
        {
            if(!Character.isDigit(c))
                evt.consume();
        }
    }//GEN-LAST:event_TimeText1KeyTyped

    private void MassText1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MassText1KeyTyped
        char c = evt.getKeyChar();
        if(!Flag_Mass)
        {
            if(c == '.')
                Flag_Mass = true;
            
            if(!Character.isDigit(c) && c != '.')
                evt.consume();
        }
        
        else
        {
            if(!Character.isDigit(c))
                evt.consume();
        }
    }//GEN-LAST:event_MassText1KeyTyped

    private void TempText1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TempText1KeyTyped
        char c = evt.getKeyChar();
        if(!Flag_Temp)
        {
            if(c == '.')
                Flag_Temp = true;
            
            if(!Character.isDigit(c) && c != '.')
                evt.consume();
        }
        
        else
        {
            if(!Character.isDigit(c))
                evt.consume();
        }
    }//GEN-LAST:event_TempText1KeyTyped

    private void SpeedText1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SpeedText1KeyTyped
        char c = evt.getKeyChar();
        if(!Flag_Speed)
        {
            if(c == '.')
                Flag_Speed = true;
            
            if(!Character.isDigit(c) && c != '.')
                evt.consume();
        }
        
        else
        {
            if(!Character.isDigit(c))
                evt.consume();
        }
    }//GEN-LAST:event_SpeedText1KeyTyped

    private void ButtonSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSignActionPerformed
        if(oprFlag)
        {
            firstNum = Double.parseDouble(Screen.getText())*-1 ; 
            String answer = String.valueOf(firstNum) ;
            Screen.setText(answer);
        }
    }//GEN-LAST:event_ButtonSignActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AreaCombo1;
    private javax.swing.JComboBox<String> AreaCombo2;
    private javax.swing.JLabel AreaLbl;
    private javax.swing.JTextField AreaText1;
    private javax.swing.JTextField AreaText2;
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonAdd;
    private javax.swing.JButton ButtonClear;
    private javax.swing.JButton ButtonConvert;
    private javax.swing.JButton ButtonDecimal;
    private javax.swing.JButton ButtonDivide;
    private javax.swing.JButton ButtonEquals;
    private javax.swing.JButton ButtonFact;
    private javax.swing.JButton ButtonMinus;
    private javax.swing.JButton ButtonModulus;
    private javax.swing.JButton ButtonMultiply;
    private javax.swing.JButton ButtonPower;
    private javax.swing.JButton ButtonRoot;
    private javax.swing.JButton ButtonSign;
    private javax.swing.JPanel CalculatorPnl;
    private javax.swing.JPanel ConversionPnl;
    private javax.swing.JLabel FromLbl;
    private javax.swing.JComboBox<String> LengthCombo1;
    private javax.swing.JComboBox<String> LengthCombo2;
    private javax.swing.JLabel LengthLbl;
    private javax.swing.JTextField LengthText1;
    private javax.swing.JTextField LengthText2;
    private javax.swing.JComboBox<String> MassCombo1;
    private javax.swing.JComboBox<String> MassCombo2;
    private javax.swing.JLabel MassLbl;
    private javax.swing.JTextField MassText1;
    private javax.swing.JTextField MassText2;
    private javax.swing.JTextField Screen;
    private javax.swing.JComboBox<String> SpeedCombo1;
    private javax.swing.JComboBox<String> SpeedCombo2;
    private javax.swing.JLabel SpeedLbl;
    private javax.swing.JTextField SpeedText1;
    private javax.swing.JTextField SpeedText2;
    private javax.swing.JComboBox<String> TempCombo1;
    private javax.swing.JComboBox<String> TempCombo2;
    private javax.swing.JLabel TempLbl;
    private javax.swing.JTextField TempText1;
    private javax.swing.JTextField TempText2;
    private javax.swing.JComboBox<String> TimeCombo1;
    private javax.swing.JComboBox<String> TimeCombo2;
    private javax.swing.JLabel TimeLbl;
    private javax.swing.JTextField TimeText1;
    private javax.swing.JTextField TimeText2;
    private javax.swing.JLabel ToLbl;
    // End of variables declaration//GEN-END:variables
}
